fix: deploy flow

diff --git a/.github/workflows/setting.yml b/.github/workflows/setting.yml
--- a/.github/workflows/setting.yml
+++ b/.github/workflows/setting.yml
@@ -23,7 +23,9 @@ jobs:
 
       - name: Enable auto-delete head branches
         run: |
-          gh repo edit ${{ github.repository }} --delete-branch-on-merge
+          gh repo edit ${{ github.repository }} \
+            --delete-branch-on-merge \
+            --default-branch develop
         env:
           GH_TOKEN: ${{ steps.generate-token.outputs.token }}
 
@@ -68,12 +70,12 @@ jobs:
 
       - name: Apply Branch Protection Rules
         run: |
-          if [ ! -f "$CONFIG_FILE" ]; then
-            echo "Error: $CONFIG_FILE not found!"
+          if [ ! -f "${{ env.CONFIG_FILE }}" ]; then
+            echo "Error: ${{ env.CONFIG_FILE }} not found!"
             exit 1
           fi
 
-          BRANCHES=$(jq -r 'keys[]' "$CONFIG_FILE")
+          BRANCHES=$(jq -r 'keys[]' "${{ env.CONFIG_FILE }}")
 
           for BRANCH in $BRANCHES; do
             if ! gh api "repos/${{ github.repository }}/branches/$BRANCH" --silent >/dev/null 2>&1; then
@@ -85,4 +87,46 @@ jobs:
           done
         env:
           CONFIG_FILE: .github/protection.json
+          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+
+  environments:
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        include:
+          - environment: Develop
+            branch: develop
+          - environment: Production
+            branch: main
+
+    environment: ${{ matrix.environment }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Generate a token
+        id: generate-token
+        uses: actions/create-github-app-token@v2
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.APP_KEY }}
+
+      - name: Configure Environment
+        run: |
+          if [ ! -f "${{ env.CONFIG_FILE }}" ]; then
+            echo "Error: ${{ env.CONFIG_FILE }} not found!"
+            exit 1
+          fi
+
+          jq -c ".\"${{ env.ENVIRONMENT_NAME }}\"" "${{ env.CONFIG_FILE }}" | gh api -X PUT "repos/${{ github.repository }}/environments/${{ env.ENVIRONMENT_NAME }}" --input -
+
+          gh api -X PUT "repos/${{ github.repository }}/environments/${{ env.ENVIRONMENT_NAME }}/deployment-branch-policies" \
+            -f "name=${{ env.ENVIRONMENT_NAME }}" \
+            -f "type=branch"
+        env:
+          CONFIG_FILE: .github/environments.json
+          BRANCH_NAME: ${{ matrix.branch }}
+          ENVIRONMENT_NAME: ${{ matrix.environment }}
           GH_TOKEN: ${{ steps.generate-token.outputs.token }}
