add: permission for workflow

diff --git a/.github/workflows/setting.yml b/.github/workflows/setting.yml
--- a/.github/workflows/setting.yml
+++ b/.github/workflows/setting.yml
@@ -11,7 +11,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  delete-branch:
+  branch:
     runs-on: ubuntu-latest
 
     steps:
@@ -28,68 +28,6 @@ jobs:
             --default-branch develop \
             --delete-branch-on-merge
         env:
-          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-
-  pages:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Generate a token
-        id: generate-token
-        uses: actions/create-github-app-token@v2
-        with:
-          app-id: ${{ vars.APP_ID }}
-          private-key: ${{ secrets.APP_KEY }}
-
-      - name: Set GitHub Pages Source
-        run: |
-          gh api -X POST ${{ env.ENDPOINT }} \
-            -f "source[branch]=${{ env.BRANCH }}" \
-            -f "source[path]=${{ env.TARGET_PATH }}" --silent \
-          || \
-          gh api -X PUT ${{ env.ENDPOINT }} \
-            -f "source[branch]=${{ env.BRANCH }}" \
-            -f "source[path]=${{ env.TARGET_PATH }}"
-        env:
-          ENDPOINT: repos/${{ github.repository }}/pages
-          BRANCH: gh-pages
-          TARGET_PATH: /
-          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-
-  protection:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v6
-
-      - name: Generate a token
-        id: generate-token
-        uses: actions/create-github-app-token@v2
-        with:
-          app-id: ${{ vars.APP_ID }}
-          private-key: ${{ secrets.APP_KEY }}
-
-      - name: Apply Branch Protection Rules
-        run: |
-          if [ ! -f ${{ env.CONFIG_FILE }} ]; then
-            echo "Error: ${{ env.CONFIG_FILE }} not found!"
-            exit 1
-          fi
-
-          BRANCHES=$(jq -r 'keys[]' ${{ env.CONFIG_FILE }})
-
-          for BRANCH in $BRANCHES; do
-            if ! gh api "${{ env.ENDPOINT }}/$BRANCH" --silent >/dev/null 2>&1; then
-              echo "Warning: Branch $BRANCH does not exist in this repository. Skipping..."
-              continue
-            fi
-
-            jq -c ".\"$BRANCH\"" ${{ env.CONFIG_FILE }} | gh api -X PUT "${{ env.ENDPOINT }}/$BRANCH/protection" --input -
-          done
-        env:
-          CONFIG_FILE: .github/protection.json
-          ENDPOINT: repos/${{ github.repository }}/branches
           GH_TOKEN: ${{ steps.generate-token.outputs.token }}
 
   environments:
@@ -143,4 +81,86 @@ jobs:
           BRANCH_NAME: ${{ matrix.branch }}
           ENDPOINT: repos/${{ github.repository }}/environments
           ENVIRONMENT_NAME: ${{ matrix.environment }}
+          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+
+  pages:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Generate a token
+        id: generate-token
+        uses: actions/create-github-app-token@v2
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.APP_KEY }}
+
+      - name: Set GitHub Pages Source
+        run: |
+          gh api -X POST ${{ env.ENDPOINT }} \
+            -f "source[branch]=${{ env.BRANCH }}" \
+            -f "source[path]=${{ env.TARGET_PATH }}" --silent \
+          || \
+          gh api -X PUT ${{ env.ENDPOINT }} \
+            -f "source[branch]=${{ env.BRANCH }}" \
+            -f "source[path]=${{ env.TARGET_PATH }}"
+        env:
+          ENDPOINT: repos/${{ github.repository }}/pages
+          BRANCH: gh-pages
+          TARGET_PATH: /
+          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+
+  permission:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Generate a token
+        id: generate-token
+        uses: actions/create-github-app-token@v2
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.APP_KEY }}
+
+      - name: Configure Actions Workflow Permissions
+        run: |
+          gh api -X PUT "${{ env.ENDPOINT }}" \
+            -f "default_workflow_permissions=write" \
+            -F "can_approve_pull_request_reviews=true"
+        env:
+          ENDPOINT: repos/${{ github.repository }}/actions/permissions/workflow
+          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+
+  protection:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Generate a token
+        id: generate-token
+        uses: actions/create-github-app-token@v2
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.APP_KEY }}
+
+      - name: Apply Branch Protection Rules
+        run: |
+          if [ ! -f ${{ env.CONFIG_FILE }} ]; then
+            echo "Error: ${{ env.CONFIG_FILE }} not found!"
+            exit 1
+          fi
+
+          BRANCHES=$(jq -r 'keys[]' ${{ env.CONFIG_FILE }})
+
+          for BRANCH in $BRANCHES; do
+            if ! gh api "${{ env.ENDPOINT }}/$BRANCH" --silent >/dev/null 2>&1; then
+              echo "Warning: Branch $BRANCH does not exist in this repository. Skipping..."
+              continue
+            fi
+
+            jq -c ".\"$BRANCH\"" ${{ env.CONFIG_FILE }} | gh api -X PUT "${{ env.ENDPOINT }}/$BRANCH/protection" --input -
+          done
+        env:
+          CONFIG_FILE: .github/protection.json
+          ENDPOINT: repos/${{ github.repository }}/branches
           GH_TOKEN: ${{ steps.generate-token.outputs.token }}
